name: sigap_mobile
description: A mobile application SIGAP

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Architecture
  get: ^4.3.8
  get_storage: ^2.0.3

  # Network
  dio: ^4.0.4
  connectivity_plus: ^2.2.1

  # UI & Widget
  flutter_svg: ^1.0.3
  double_back_to_close_app: ^2.0.1
  keyboard_dismisser: ^2.0.0
  material_design_icons_flutter: ^5.0.6595
  pin_code_fields: ^7.3.0
  introduction_screen: ^2.1.0

  # Animation
  lottie: ^1.2.1
  flutter_spinkit: ^5.1.0

  # Picker
  path_provider: ^2.0.8
  camera: ^0.9.4+16
  image_picker: ^0.8.4+11
  file_picker: ^4.5.1
  open_file: ^3.2.1
  flutter_image_compress: ^1.1.0

  # Notifications
  flutter_local_notifications: ^9.4.0
  #firebase_core: ^1.12.0
  #firebase_messaging: ^11.2.7
  #firebase_analytics: ^9.1.1
  rxdart: ^0.27.3

  # Others
  intl: ^0.17.0
  permission_handler: ^9.2.0
  supercharged: ^2.1.1
  fluttertoast: ^8.0.5

  # Testing
  equatable: ^2.0.3
  mockito: ^5.1.0
  http_mock_adapter: ^0.3.2
  get_test: ^4.0.0
  build_runner: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300