// Mocks generated by Mockito 5.1.0 from annotations
// in sigap_mobile/test/controller/login_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sigap_mobile/data/data_source/server/auth_datasource/auth_datasource.dart'
    as _i3;
import 'package:sigap_mobile/data/model/account.dart' as _i5;
import 'package:sigap_mobile/data/model/base_response.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeApiResponse_0<T> extends _i1.Fake implements _i2.ApiResponse<T> {}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i3.AuthDataSource {
  MockAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.Account>> login(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #login, [], {#username: username, #password: password}),
              returnValue: Future<_i2.ApiResponse<_i5.Account>>.value(
                  _FakeApiResponse_0<_i5.Account>()))
          as _i4.Future<_i2.ApiResponse<_i5.Account>>);
}
